import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const DOCS = '/home/claude/tresD_DICOM/docs', OUT = '/home/claude/tresD_DICOM/tests/out';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.wasm': 'application/wasm', '.png': 'image/png', '.woff2': 'font/woff2' };
const server = http.createServer((req, res) => { let p = decodeURIComponent(req.url.split('?')[0]); if (p === '/') p = '/index.html'; const f = path.join(DOCS, p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); res.end(); return; } res.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res); });
await new Promise((r) => server.listen(8784, r));
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1500, height: 900 }, locale: 'es-ES' });
await page.addInitScript(() => { try { localStorage.setItem('tresd_dicom_terms', 'v1-2026-09'); } catch (e) {} });
page.setDefaultTimeout(300000);
await page.goto('http://localhost:8784/'); await page.waitForTimeout(600);
await page.setInputFiles('#in-folder', '/tmp/testdata/cbct_half');
await page.waitForFunction(() => /^(Cargado|Aviso|Error)/.test(document.querySelector('#status-text').textContent), null, { timeout: 300000 });
await page.click('[data-layout="vpPan"]');
await page.waitForFunction(() => window.tresd.V.state.pano && document.querySelector('#pan-canvas').width > 100, null, { timeout: 300000 });
await page.waitForTimeout(800);
const box = await page.locator('#vpPan').boundingBox();
await page.screenshot({ path: path.join(OUT, 'pano_mip2.png'), clip: box });
await page.click('#pan-mip'); await page.waitForTimeout(2500);
await page.screenshot({ path: path.join(OUT, 'pano_sum2.png'), clip: box });
console.log('ok', JSON.stringify(await page.evaluate(() => window.tresd.V.getPanoWindow())));
await browser.close(); server.close();
